services:
    _defaults:
        autowire: false
        autoconfigure: true
        public: false

    Cowegis\ContaoGeocoder\EventListener\Dca\ProviderDcaListener:
        public: true
        arguments:
            - '@netzmacht.contao_toolkit.dca.manager'
            - '@Cowegis\ContaoGeocoder\Provider\ProviderFactory'
            - '@Cowegis\ContaoGeocoder\Provider\Geocoder'
            - '@database_connection'

    Cowegis\ContaoGeocoder\EventListener\Hook\BackendListener:
        arguments:
            - '@netzmacht.contao_toolkit.routing.scope_matcher'
            - '@netzmacht.contao_toolkit.assets_manager'
